const terrain = {
  open: {
    name: 'Open',
    msMul: 1,
    exceptions: [],
    defBonusMul: 1,
  },
  track: {
    name: 'Track',
    msMul: 1.5,
    exceptions: [
      { class: 'Flying', msMul: 1 },
      { class: 'Titan', msMul: 1 },
    ],
    defBonusMul: 1,
  },
  bridge: {
    name: 'Bridge',
    msMul: 1.5,
    exceptions: [
      { class: 'Flying', msMul: 1 },
      { class: 'Titan', msMul: 1 },
    ],
    defBonusMul: 1,
  },
  structure: {
    name: 'Structure',
    msMul: 1,
    exceptions: [],
    defBonusMul: 1.25,
  },
  swamp: {
    name: 'Swamp',
    msMul: 0.33,
    exceptions: [
      { class: 'Amphibious', msMul: 1 },
      { class: 'Flying', msMul: 1 },
      { class: 'Titan', msMul: 1 },
    ],
    defBonusMul: 1.1,
  },
  river: {
    name: 'River',
    msMul: 0,
    exceptions: [
      { class: 'Scout', msMul: 0.33 },
      { class: 'Amphibious', msMul: 1 },
      { class: 'Elemental of Elidinis', msMul: 3 },
      { class: 'Flying', msMul: 1 },
      { class: 'Titan', msMul: 1 },
    ],
    defBonusMul: 1.1,
  },
  sea: {
    name: 'Sea',
    msMul: 0,
    exceptions: [
      { class: 'Amphibious', msMul: 1 },
      { class: 'Elemental of Elidinis', msMul: 3 },
      { class: 'Flying', msMul: 1 },
    ],
    defBonusMul: 1,
  },
  forest: {
    name: 'Forest',
    msMul: 0.5,
    exceptions: [
      { race: 'Guthix', msMul: 1 },
      { class: 'Flying', msMul: 1 },
      { class: 'Titan', msMul: 1 },
    ],
    defBonusMul: 1.25,
  },
  mountain: {
    name: 'mountain',
    msMul: 0,
    exceptions: [
      { race: 'Ourg', msMul: 0.33 },
      { class: 'Flying', msMul: 1 },
    ],
    defBonusMul: 1.4,
  },
};

structures = {
  village: {
    name: 'Village',
    strength: 10,
    manaPT: 25,
  },
  portal: {
    name: 'Portal',
    strength: 10,
    manaPT: 50,
  },
  tower: {
    name: 'Tower',
    strength: 15,
    manaPT: 75,
  },
  temple: {
    name: 'Temple',
    strength: 15,
    manaPT: 75,
  },
};
races = {
  saradomin: {
    units: {
      monk: {
        name: 'Monk',
        class: 'Healer',
        level: 1,
        speed: 6,
        strength: 10,
        range: 1,
        cost: 150,
        description: '',
      },
      paladin: {
        name: 'Paladin',
        class: 'Warrior',
        level: 1,
        speed: 6,
        strength: 10,
        range: 1,
        cost: 100,
        description: '',
      },
      saradominOwl: {
        name: 'Saradomin Owl',
        class: 'Flying',
        level: 1,
        speed: 6,
        strength: 5,
        range: 1,
        cost: 100,
        description: '',
      },
      saradominRanger: {
        name: 'Saradomin Ranger',
        class: 'Ranged',
        level: 2,
        speed: 6,
        strength: 20,
        range: [2, 3],
        cost: 200,
        description: '',
      },
      whiteKnight: {
        name: 'White Knight',
        class: 'Warrior',
        level: 2,
        speed: 5,
        strength: 25,
        range: 1,
        cost: 250,
        description: '',
      },
      saradominMage: {
        name: 'Saradomin Mage',
        class: 'Mage',
        level: 3,
        speed: 3,
        strength: 20,
        range: [3, 5],
        cost: 250,
        description: '',
      },
      lion: {
        name: 'Lion',
        class: 'Warrior',
        level: 3,
        speed: 4,
        strength: 40,
        range: 1,
        cost: 350,
        description: '',
      },
      unicorn: {
        name: 'Unicorn',
        class: 'Scout',
        level: 3,
        speed: 8,
        strength: 30,
        range: 1,
        cost: 350,
        description: '',
      },
      centaur: {
        name: 'Centaur',
        class: 'Ranged',
        level: 4,
        speed: 9,
        strength: 25,
        range: [1, 3],
        cost: 300,
        description: '',
      },
      priest: {
        name: 'Priest',
        class: 'Healer',
        level: 4,
        speed: 6,
        strength: 20,
        range: 1,
        cost: 300,
        description: '',
      },
      icyene: {
        name: 'Icyene',
        class: 'Flying',
        level: 5,
        speed: 8,
        strength: 40,
        range: [1, 3],
        cost: 800,
        description: '',
      },
    },
  },
  zamorak: {
    units: {
      werewolf: {
        name: 'Werewolf',
        class: 'Warrior',
        level: 1,
        speed: 6,
        strength: 10,
        range: 1,
        cost: 100,
        description: '',
      },
      skeleton: {
        name: 'Skeleton',
        class: 'Scout',
        level: 1,
        speed: 5,
        strength: 15,
        range: 1,
        cost: 100,
        description: '',
      },
      necromancer: {
        name: 'Necromancer',
        class: 'Healer',
        level: 1,
        speed: 6,
        strength: 10,
        range: 1,
        cost: 150,
        description: '',
      },
      zamorakRanger: {
        name: 'Zamorak Ranger',
        class: 'Ranged',
        level: 2,
        speed: 6,
        strength: 20,
        range: [2, 3],
        cost: 200,
        description: '',
      },
      blackKnight: {
        name: 'Black Knight',
        class: 'Warrior',
        level: 2,
        speed: 5,
        strength: 25,
        range: 1,
        cost: 250,
        description: '',
      },
      zamorakMage: {
        name: 'Zamorak Mage',
        class: 'Mage',
        level: 3,
        speed: 3,
        strength: 20,
        range: [3, 5],
        cost: 250,
        description: '',
      },
      hellhound: {
        name: 'Hellhound',
        class: 'Scout',
        level: 3,
        speed: 8,
        strength: 30,
        range: 1,
        cost: 350,
        description: '',
      },
      seaSlug: {
        name: 'Sea Slug',
        class: 'Scout',
        level: 3,
        speed: 3,
        strength: 10,
        range: 1,
        cost: 100,
        description: '',
      },
      greaterDemon: {
        name: 'Greater Demon',
        class: 'Warrior',
        level: 4,
        speed: 4,
        strength: 50,
        range: 1,
        cost: 450,
        description: '',
      },
      gargoyle: {
        name: 'Gargoyle',
        class: 'Flying',
        level: 4,
        speed: 6,
        strength: 30,
        range: [1, 3],
        cost: 600,
        description: '',
      },
      pyreflord: {
        name: 'Pyrelord',
        class: 'Titan',
        level: 5,
        speed: 3,
        strength: 50,
        range: 1,
        cost: 750,
        description: '',
      },
    },
  },
  guthix: {
    units: {
      wolf: {
        name: 'Wolf',
        class: 'Scout',
        level: 1,
        speed: 8,
        strength: 10,
        range: 1,
        cost: 150,
        description: '',
      },
      druid: {
        name: 'Druid',
        class: 'Healer',
        level: 1,
        speed: 6,
        strength: 10,
        range: 1,
        cost: 150,
        description: '',
      },
      blackGuardDwarf: {
        name: 'Black Guard Dwarf',
        class: 'Healer',
        level: 1,
        speed: 6,
        strength: 10,
        range: 1,
        cost: 150,
        description: '',
      },
      zamorakRanger: {
        name: 'Zamorak Ranger',
        class: 'Ranged',
        level: 2,
        speed: 6,
        strength: 20,
        range: [2, 3],
        cost: 200,
        description: '',
      },
      blackKnight: {
        name: 'Black Knight',
        class: 'Warrior',
        level: 2,
        speed: 5,
        strength: 25,
        range: 1,
        cost: 250,
        description: '',
      },
      zamorakMage: {
        name: 'Zamorak Mage',
        class: 'Mage',
        level: 3,
        speed: 3,
        strength: 20,
        range: [3, 5],
        cost: 250,
        description: '',
      },
      hellhound: {
        name: 'Hellhound',
        class: 'Scout',
        level: 3,
        speed: 8,
        strength: 30,
        range: 1,
        cost: 350,
        description: '',
      },
      seaSlug: {
        name: 'Sea Slug',
        class: 'Scout',
        level: 3,
        speed: 3,
        strength: 10,
        range: 1,
        cost: 100,
        description: '',
      },
      greaterDemon: {
        name: 'Greater Demon',
        class: 'Warrior',
        level: 4,
        speed: 4,
        strength: 50,
        range: 1,
        cost: 450,
        description: '',
      },
      gargoyle: {
        name: 'Gargoyle',
        class: 'Flying',
        level: 4,
        speed: 6,
        strength: 30,
        range: [1, 3],
        cost: 600,
        description: '',
      },
      pyreflord: {
        name: 'Pyrelord',
        class: 'Titan',
        level: 5,
        speed: 3,
        strength: 50,
        range: 1,
        cost: 750,
        description: '',
      },
    },
  },
};

// monk: {
//   name: '',
//   class: '',
//   level: ,
//   speed: ,
//   strength: ,
//   range: ,
//   cost: ,
//   description: '',
// },

module.exports = {
  terrain,
  structures,
  races,
};
