races = {
  saradomin: {
    units: {
      monk: {
        name: 'Monk',
        class: 'Healer',
        level: 1,
        speed: 6,
        strength: 10,
        range: 1,
        cost: 150,
        description: '',
      },
      paladin: {
        name: 'Paladin',
        class: 'Warrior',
        level: 1,
        speed: 6,
        strength: 10,
        range: 1,
        cost: 100,
        description: '',
      },
      saradominOwl: {
        name: 'Saradomin Owl',
        class: 'Flying',
        level: 1,
        speed: 6,
        strength: 5,
        range: 1,
        cost: 100,
        description: '',
      },
      saradominRanger: {
        name: 'Saradomin Ranger',
        class: 'Ranged',
        level: 2,
        speed: 6,
        strength: 20,
        range: [2, 3],
        cost: 200,
        description: '',
      },
      whiteKnight: {
        name: 'White Knight',
        class: 'Warrior',
        level: 2,
        speed: 5,
        strength: 25,
        range: 1,
        cost: 250,
        description: '',
      },
      saradominMage: {
        name: 'Saradomin Mage',
        class: 'Mage',
        level: 3,
        speed: 3,
        strength: 20,
        range: [3, 5],
        cost: 250,
        description: '',
      },
      lion: {
        name: 'Lion',
        class: 'Warrior',
        level: 3,
        speed: 4,
        strength: 40,
        range: 1,
        cost: 350,
        description: '',
      },
      unicorn: {
        name: 'Unicorn',
        class: 'Scout',
        level: 3,
        speed: 8,
        strength: 30,
        range: 1,
        cost: 350,
        description: '',
      },
      centaur: {
        name: 'Centaur',
        class: 'Ranged',
        level: 4,
        speed: 9,
        strength: 25,
        range: [1, 3],
        cost: 300,
        description: '',
      },
      priest: {
        name: 'Priest',
        class: 'Healer',
        level: 4,
        speed: 6,
        strength: 20,
        range: 1,
        cost: 300,
        description: '',
      },
      icyene: {
        name: 'Icyene',
        class: 'Flying',
        level: 5,
        speed: 8,
        strength: 40,
        range: [1, 3],
        cost: 800,
        description: '',
      },
    },
  },
};

// monk: {
//   name: '',
//   class: '',
//   level: ,
//   speed: ,
//   strength: ,
//   range: ,
//   cost: ,
//   description: '',
// },

console.log(races);
